# Generated by Django 5.2.6 on 2025-09-19 18:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='offline_exports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('visiting_hours', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('cultural_notes', models.JSONField(blank=True, default=dict)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Panorama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='panoramas/')),
                ('image_lite', models.ImageField(blank=True, null=True, upload_to='panoramas/lite/')),
                ('is_primary', models.BooleanField(default=False)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monastery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panoramas', to='api.monastery')),
            ],
        ),
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('pitch', models.FloatField(default=0.0)),
                ('yaw', models.FloatField(default=0.0)),
                ('language_content', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('panorama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='api.panorama')),
            ],
        ),
        migrations.AddIndex(
            model_name='monastery',
            index=models.Index(fields=['slug'], name='api_monaste_slug_23dfe6_idx'),
        ),
        migrations.AddIndex(
            model_name='monastery',
            index=models.Index(fields=['latitude', 'longitude'], name='api_monaste_latitud_fc9b2f_idx'),
        ),
    ]
