# Generated by Django 5.2.6 on 2025-09-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('iframe_url', models.URLField(blank=True, help_text='Google 360° tour iframe URL')),
                ('virtual_image', models.FileField(blank=True, null=True, upload_to='monastery_360/')),
            ],
        ),
    ]
